#!/bin/bash
#
# Copyright (C) 2023 Thomas Mueller (tm-dd)
#
# This code is free software. You can use, redistribute and/or
# modify it under the terms of the GNU General Public Licence
# version 2, as published by the Free Software Foundation.
# This program is distributed without any warranty.
# See the GNU General Public Licence for more details.
#

# the new name of the certificate 
userLogin="$1"

## START SETTINGS

# read settings from config.cfg
source "`dirname $0`/config.cfg"

# settings for the permitted use of the certificate
cat << STOPWRITE > ${caClientExtFile}
[client_req_ext]
keyUsage = digitalSignature
extendedKeyUsage = clientAuth
STOPWRITE

## END OF SETTINGS

# if missing, create this folders
mkdir -p "${caClientCertFolder}" "${caClientKeysFolder}"
chown root:root "${caClientKeysFolder}" || exit -1
chmod 700 "${caClientKeysFolder}"

# check if parameter is missing
if [ -z "${userLogin}" ]
then

	echo "ERROR: USAGE $0 CN_NAME_FOR_THE_NEW_CERTIFICATE"
	echo "Example: $0 login"
	exit -1
fi

# check and stop, if a client certificate still exists
if [ -e "${caClientKeyFile}" ] || [ -e "${caClientCrtFile}" ]
then
	echo "ERROR: A OLDER CERTIFICATE FOR ${userLogin} EXITS."
	echo "Reactivate, remove or rename the older certificate (and retry it again)."
	ls -l "${caClientKeyFile}" "${caClientCsrFile}" "${caClientCrtFile}" 2> /dev/null
	exit -1
fi

set -x

# create the client key
openssl genrsa -out "${caClientKeyFile}" -rand "${caPrivateRand}" 4096

# create the certificates request
openssl req -newkey rsa:4096 -key "${caClientKeyFile}" -out "${caClientCsrFile}" -subj "${caCertSubjectStart}/CN=${userLogin}"
openssl req -in "${caClientCsrFile}" -text -noout

# sign the certificate and move the certificates request to the temp folder (for later deleting)
openssl x509 -req -CA "${caCrtFile}" -CAkey "${caKeyFile}" -in "${caClientCsrFile}" -out "${caClientCrtFile}" -sha512 -extfile "${caClientExtFile}" -extensions "client_req_ext" -days ${caClientCertValidDays}

# read the certificate
openssl x509 -in "${caClientCrtFile}" -text -noout

# write the serial number
caClientSerialNumber=`openssl x509 -in "${caClientCrtFile}" -text -noout | grep -A 1 'Serial Number:' | tail -n 1 | sed 's/://g' | awk '{ print $1 }'`
echo -e "V\t"`date '+%y%m%d%H%M%SZ'`"\t\t${caClientSerialNumber}\tunknown\t${caCertSubjectStart}/CN=${userLogin}" >> "${caClientIndexFile}"

mv "${caClientCsrFile}" /tmp/

cat "${caFolder}index.txt"

# create certificate chain
cat "${caCrtFile}" "${caClientCrtFile}" > "${caClientCrtChainFile}"

set +x

# list the new files
if [ -e "${caClientKeyFile}" ] && [ -e "${caClientCrtFile}" ] && [ -e "${caClientCrtChainFile}" ]
then
	echo "NEW FILES:"
	ls -l "${caClientKeyFile}" "${caClientCrtFile}" "${caClientCrtChainFile}"
else
	echo "Error durring ceation of files..."
	exit -1
fi

exit 0;
